plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Disabled to be consistent with Standard Ruby
Style/RescueStandardError:
  Enabled: false

# Disabled to be consistent with Standard Ruby
Style/EmptyMethod:
  Enabled: false

# Disabled to be consistent with Standard Ruby
Layout/ArgumentAlignment:
  Enabled: false

# Disabled to be consistent with Standard Ruby
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# Disabled because the string references are intentional (the classes don't exist)
RSpec/VerifiedDoubleReference:
  Enabled: false

# Only disabled for the serializable spec where Marshal.load is legitimately tested
Security/MarshalLoad:
  Exclude:
    - "spec/integration/serializable_spec.rb"

# Allow more memoized helpers in complex test setups
RSpec/MultipleMemoizedHelpers:
  Max: 10
